/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/interior.glb -T 
Files: public/interior.glb [10.06MB] > C:\Users\Hamza Computers\Desktop\React\3DSoft\ibtikarz-villa-explorer\interior-transformed.glb [1.32MB] (87%)
Author: Katydid (https://sketchfab.com/Katydid.)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-apartment-interior-400c9069181a4342a7142433dfa3466e
Title: Modern apartment interior
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
export default function Interior(props) {
  const { nodes, materials } = useGLTF('/interior-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color646464255} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2.geometry} material={materials.material_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material2_1.geometry} material={materials.auto} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3.geometry} material={materials.auto_1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_1.geometry} material={materials.auto_2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_2.geometry} material={materials.auto_3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_3.geometry} material={materials.auto_6} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_4.geometry} material={materials.auto_4} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_5.geometry} material={materials.auto_5} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_6.geometry} material={materials.auto_7} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_7.geometry} material={materials.auto_8} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_8.geometry} material={materials.auto_9} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_9.geometry} material={materials.auto_11} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_10.geometry} material={materials.auto_10} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_11.geometry} material={materials.auto_12} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_12.geometry} material={materials.auto_14} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_13.geometry} material={materials.auto_16} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_14.geometry} material={materials.auto_18} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_15.geometry} material={materials.auto_20} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_16.geometry} material={materials.auto_23} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_17.geometry} material={materials.auto_22} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_18.geometry} material={materials.auto_24} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_19.geometry} material={materials.auto_25} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_20.geometry} material={materials.auto_27} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_21.geometry} material={materials.auto_28} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_22.geometry} material={materials.auto_29} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_23.geometry} material={materials.auto_30} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_24.geometry} material={materials.auto_33} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_25.geometry} material={materials.auto_34} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_26.geometry} material={materials.auto_35} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_27.geometry} material={materials.auto_38} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_28.geometry} material={materials.auto_37} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_29.geometry} material={materials.auto_39} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_30.geometry} material={materials.auto_40} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_31.geometry} material={materials.auto_41} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_32.geometry} material={materials.auto_43} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_33.geometry} material={materials.auto_45} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_34.geometry} material={materials.auto_47} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_35.geometry} material={materials.auto_48} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_36.geometry} material={materials.auto_49} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_37.geometry} material={materials.auto_51} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_38.geometry} material={materials.auto_54} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Material3_39.geometry} material={materials.auto_55} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/interior-transformed.glb')
